Rend index and creation
wolox-training/fp-rails pull request #11
Opened 2019-06-03 20:27 UTC by HarryPerez

## Summary
#### Added rent index and create endpoints

## Screenshots
<img width="1680" alt="Captura de Pantalla 2019-06-03 a la(s) 17 27 06" src="https://user-images.githubusercontent.com/36163179/58832227-e0349d80-8624-11e9-8f59-0090236804da.png">
<img width="1680" alt="Captura de Pantalla 2019-06-03 a la(s) 17 27 13" src="https://user-images.githubusercontent.com/36163179/58832228-e0349d80-8624-11e9-92c3-74f0ddb1ecf9.png">
<img width="1680" alt="Captura de Pantalla 2019-06-03 a la(s) 17 27 23" src="https://user-images.githubusercontent.com/36163179/58832230-e0cd3400-8624-11e9-896b-a12a32dc0590.png">

## Trello Card
https://trello.com/c/C4VJi17k/28-crear-endpoint-de-creacion-de-rent-e-index

2019-06-04 19:57 UTC, Gmarn requested changes

2019-06-04 19:57 UTC, Gmarn commented on app/controllers/v1/rents_controller.rb
> +      rent = Rent.create!(rent_params)
Hummmm, no! Este punto de exclamacion? :so-loco-vos: ?

2019-06-04 19:57 UTC, Gmarn commented on app/controllers/v1/rents_controller.rb
> +      rent = Rent.create!(rent_params)
Podemos itentar un flujo con new and save y manejar el caso de un reocrd invalid con `rescue_from`?

2019-06-04 19:57 UTC, Gmarn commented on app/controllers/v1/rents_controller.rb
> +      render_paginated Rent
Clap 👍

2019-06-04 19:57 UTC, Gmarn commented on app/controllers/v1/rents_controller.rb
> +  class RentsController < ApiController
Question: Estos end points son authenticado?

2019-08-06 17:03 UTC, HarryPerez commented on app/controllers/v1/rents_controller.rb
> +  class RentsController < ApiController
Yes why not?

2019-08-06 17:04 UTC, HarryPerez commented on app/controllers/v1/rents_controller.rb
> +      render_paginated Rent
👏

2019-08-06 17:04 UTC, HarryPerez commented on app/controllers/v1/rents_controller.rb
> +      rent = Rent.create!(rent_params)
![tenor-229695651](https://user-images.githubusercontent.com/36163179/62560309-268bc000-b853-11e9-98f5-b6402ccba58a.gif)

2019-08-06 17:07 UTC, HarryPerez commented on app/controllers/v1/rents_controller.rb
> +      rent = Rent.create!(rent_params)
What did you want to say with `new` and `save`?

2019-08-06 18:36 UTC, Gmarn submitted a review, later dismissed

2019-08-06 21:04 UTC, Gmarn approved these changes

2019-08-07 15:31 UTC, merged